# Generated by Django 3.2 on 2021-04-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='statusCode',
            field=models.IntegerField(blank=True, default=200),
        ),
    ]
