# Generated by Django 3.2 on 2021-04-10 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0002_alter_sms_statuscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='group_name',
            field=models.ForeignKey(default='General contacts', on_delete=django.db.models.deletion.CASCADE, to='smsApp.recipientgroup'),
        ),
    ]
