# Generated by Django 3.2 on 2021-04-10 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0003_alter_recipient_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='group_name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='smsApp.recipientgroup'),
        ),
        migrations.AlterField(
            model_name='recipientgroup',
            name='group_name',
            field=models.CharField(default='General contacts', max_length=30),
        ),
    ]
