# Generated by Django 3.2 on 2021-04-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0004_auto_20210410_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='cost',
            field=models.CharField(default='MWK 0.0000', max_length=13),
        ),
    ]
