# Generated by Django 3.2 on 2021-04-15 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0005_sms_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='phone_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smsApp.recipient'),
        ),
    ]
