# Generated by Django 3.2 on 2021-04-15 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0008_alter_sms_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='group_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smsApp.recipientgroup'),
        ),
    ]
