# Generated by Django 3.2 on 2021-04-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0009_sms_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
