# Generated by Django 3.2 on 2021-04-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0011_auto_20210420_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
